# -*- coding: utf-8 -*-
"""9_konlpy.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1z2T4OUg-noMoSnZykLtpps1VPZtJw23O
"""

!pip install konlpy

import konlpy
from konlpy.tag import Okt

!ls -l '/usr/lib/jvm'

text = "머신러닝을 공부하고 있습니다. 너무 재미있습니다."
okt = Okt() #인스턴스화

#형태소 분리
print(okt.morphs(text))
print(okt.morphs(text, stem=True)) # 어간 추출

#명사 추출
print(okt.nouns(text))

#어절 추출
print(okt.phrases(text))

#품사 태깅
print(okt.pos(text))
print(okt.pos(text, join=True))

